name: Run UI and API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Force Chrome in config
        run: echo "browser=chrome" > src/test/resources/config.properties

#      - name: Run Tests with Maven
#        run: mvn clean test
      - name: Run Tests with Maven
        run: mvn clean test -Daut.browser=chrome -Dsurefire.useFile=false

      - name: Upload Surefire Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/

      - name: Upload ExtentReport
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-report
          path: test-output/




