name: Run UI and API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      # ✅ Dynamically set config.properties with all required keys
      - name: Set up config.properties
        run: |
          echo "browser=chrome" > src/test/resources/config.properties
          echo "aut.baseUrl=https://www.saucedemo.com/" >> src/test/resources/config.properties
          echo "aut.username=standard_user" >> src/test/resources/config.properties
          echo "aut.password=secret_sauce" >> src/test/resources/config.properties
          echo "aut.firstName=John" >> src/test/resources/config.properties
          echo "aut.lastName=Doe" >> src/test/resources/config.properties
          echo "aut.zip=12345" >> src/test/resources/config.properties
          echo "ui.checkout.fullMessage=Thank you for your order! Your order has been dispatched, and will arrive jus
